defaults:
  working_directory: ~/repo

version: 2.0
jobs:
  build:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Branch }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ~/.cache
      - run:
          name: Run Test and Coverage
          command: npm test -- --coverage
      - run:
          name: Background the app
          command: npm start
          background: true
      - run:
          name: Run e2e test with Cypress
          command: npm run test:e2e:run -- --reporter junit --reporter-options "mochaFile=results/my-test-output.xml"
          when: on_success
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - store_test_results:
          path: results
